version: '3.8'

services:
  telegram-bot:
    build: .
    volumes:
      - ./media:/app/media
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - YOOMONEY_PROVIDER_TOKEN=${YOOMONEY_PROVIDER_TOKEN}
      - STUDENTS_CHAT_ID=${STUDENTS_CHAT_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; import requests; try: r = requests.get('https://api.telegram.org/bot' + open('/app/.env').read().split('BOT_TOKEN=')[1].split('\\n')[0] + '/getMe'); sys.exit(0 if r.status_code == 200 else 1) except Exception: sys.exit(1)"]      interval: 30s
      timeout: 10s
      retries: 3
