name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          # Setup SSH directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Write private key to standard SSH key file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add host to known hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          # Create SSH config file
          cat > ~/.ssh/config << EOF
          Host *
            IdentityFile ~/.ssh/id_rsa
            UserKnownHostsFile ~/.ssh/known_hosts
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config
          
          # If key has a passphrase, add it to ssh-agent
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | SSH_ASKPASS=/usr/bin/ssh-add ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: |
          # Test with verbose output and explicit key file
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful!'"

      - name: Deploy to VPS
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "Creating project directory on VPS..."
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p ~/anna-telegram-bot"
          
          echo "Syncing repository to VPS..."
          rsync -avz --progress --delete \
            --exclude='.env' \
            --exclude='media/*' \
            --exclude='data/*' \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/anna-telegram-bot/

      - name: Configure and start bot
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "Setting up permissions and starting bot..."
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/anna-telegram-bot && \
            chmod +x start.sh stop.sh entrypoint.sh && \
            ./stop.sh || true && \
            ./start.sh"

      - name: Check deployment status
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "Checking deployment status..."
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/anna-telegram-bot && \
            docker compose ps && \
            docker compose logs --tail=50"

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up sensitive files..."
          rm -f ~/.ssh/deploy_key
